# Generated by Django 5.0.13 on 2025-03-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hex_code', models.CharField(max_length=7, unique=True)),
                ('rgb', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='colors/')),
            ],
        ),
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('source_url', models.URLField()),
                ('colors', models.ManyToManyField(related_name='palettes', to='scraper.color')),
            ],
        ),
    ]
