# Generated by Django 5.0.13 on 2025-03-22 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='name',
        ),
        migrations.RemoveField(
            model_name='palette',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='palette',
            name='name',
        ),
        migrations.RemoveField(
            model_name='palette',
            name='source_url',
        ),
        migrations.AddField(
            model_name='color',
            name='names',
            field=models.TextField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='color',
            name='source',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='palette',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='src/images/palettes/'),
        ),
        migrations.AddField(
            model_name='palette',
            name='palette_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='palette',
            name='source',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='image',
            field=models.ImageField(upload_to='src/images/colors/'),
        ),
        migrations.CreateModel(
            name='PaletteColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palette_color1', to='scraper.color')),
                ('color2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palette_color2', to='scraper.color')),
                ('color3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palette_color3', to='scraper.color')),
                ('color4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='palette_color4', to='scraper.color')),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.palette')),
            ],
        ),
    ]
